name: Squash commits in branch

on:
  # workflow_dispatch
  pull_request:
    types: [ labeled ]
    branches: [ master ]
    # types: [ opened, synchronize, edited, ready_for_review ]

jobs:
  squash-commits:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'squash' }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Config author
      run: |
        git config user.name "${{github.event.pull_request.user.login}}"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
    - name: Reset history
      run: |
        git switch ${{ github.head_ref }}
        git reset $(git merge-base origin/master HEAD)
        git status
    - name: Make a commit 
      run: |
        git add -A
        git commit -m "${{ github.event.pull_request.title }}"
    - name: Push to origin
      run: git push origin origin/${{ github.head_ref || github.ref_name }} --force
    # - run: exit 0
    - name: 'Remove label squash'
      uses: actions/github-script@v6
      with:
        script: |
          setTimeout(() => {
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["squash"]
            })
          }, 10000)
