name: Squash commits in branch

on:
  pull_request:
    types: [ labeled ]
    branches: [ master ]

jobs:
  squash-commits:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'squash' }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        persist-credentials: false
    - name: Config author
      run: |
        git config --local user.name "${{github.event.pull_request.user.login}}"
        git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
    - name: Reset history
      run: |
        git switch ${{ github.head_ref }}
        git reset $(git merge-base origin/master HEAD)
        git status
    - name: Make a commit 
      run: |
        git add -A
        git commit -m "${{ github.event.pull_request.title }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        force: true
    - name: removelabel
      uses: buildsville/add-remove-label@v2.0.0
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        labels: squash
        type: remove
